[features]
seeds = false
skip-lint = false
[programs.localnet]
counter_solang = "EzJ5QJn9AcXz3Mu9Ph2MYHiJ5j7ER3fexNeokeWMTYzD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/chuo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
